name: spdx_license_fetcher
description: Dart package to scan my project directory for license files and read the content of identified license files
version: 0.1.0
environment:
  sdk: ^3.4.1
dependencies:
  string_similarity: ^2.0.0
dev_dependencies:
  test: ^1.25.5